apiVersion: harness.io/v1
kind: Component
type: service
identifier: t_kroger455ip24
name: t-kroger455ip24
owner: group:account/Kroger
orgIdentifier: kroger455org
projectIdentifier: kroger455ip24
spec:
  lifecycle: experimental
metadata:
  description: t-kroger455ip24
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/harnessworkshop/t-kroger455ip24/tree/main/t-kroger455ip24
    backstage.io/source-location: url:https://github.com/harnessworkshop/t-kroger455ip24
  links:
  - title: Website
    url: https://harness.io
  tags:
  - my-sample
